name: rapidcuration_extras
channels:
  - bioconda
dependencies:
  - bioconda::pyfastaq
  - bioconda::perl-bioperl
  - bioconda::pretextgraph
  - bioconda::biopython
  - bioconda::kmer-jellyfish
  - bioconda::ucsc-bigwigtobedgraph